# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weighttype',
            name='human_weight',
            field=models.IntegerField(default=150),
        ),
        migrations.AlterField(
            model_name='weighttype',
            name='weight',
            field=models.IntegerField(default=45),
        ),
    ]
