# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_auto_20161001_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackWorkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_type', models.CharField(max_length=50)),
                ('weight', models.IntegerField(default=45)),
                ('reps', models.IntegerField()),
                ('sets_reps', models.IntegerField()),
                ('comments', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='workouttrack',
            name='reps',
        ),
        migrations.DeleteModel(
            name='WeightType',
        ),
        migrations.DeleteModel(
            name='WorkoutTrack',
        ),
    ]
