# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_auto_20161004_0131'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyMassIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('human_weight', models.FloatField(default=66)),
                ('human_height', models.FloatField(default=178)),
            ],
        ),
        migrations.DeleteModel(
            name='TrackWorkout',
        ),
    ]
