# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0004_auto_20161004_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodymassindex',
            name='human_height',
            field=models.FloatField(default=70),
        ),
        migrations.AlterField(
            model_name='bodymassindex',
            name='human_weight',
            field=models.FloatField(default=145),
        ),
    ]
