# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0005_auto_20161004_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('human_weight', models.FloatField(default=145, help_text='Enter weight in pounds')),
                ('human_height', models.FloatField(default=70, help_text='Enter height in inches')),
            ],
        ),
        migrations.DeleteModel(
            name='BodyMassIndex',
        ),
    ]
