# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0006_auto_20161004_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='human_height',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='human_height_ft',
            field=models.IntegerField(default=5, help_text='Enter height in feet'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='human_height_in',
            field=models.IntegerField(default=10, help_text='Enter height in inches'),
        ),
    ]
