# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0007_auto_20161006_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='human_height_ft',
            field=models.IntegerField(default=5, help_text='Enter height in feet', max_length=7),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='human_height_in',
            field=models.IntegerField(default=10, help_text='Enter height in inches', max_length=12),
        ),
    ]
