# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0011_auto_20161008_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='workouttype',
            name='days',
            field=models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], default=1, max_length=1),
        ),
    ]
