# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0012_workouttype_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='workouttype',
            name='days',
        ),
        migrations.AddField(
            model_name='workouttype',
            name='days',
            field=models.ManyToManyField(to='fitness.Days'),
        ),
    ]
