# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0017_auto_20161015_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouttype',
            name='Workout_end',
            field=models.TimeField(blank=True, default='test'),
        ),
        migrations.AlterField(
            model_name='workouttype',
            name='workout_start',
            field=models.DateTimeField(),
        ),
    ]
